package hibernate;
// Generated Jun 3, 2016 4:28:59 PM by Hibernate Tools 3.6.0



/**
 * Karyawan generated by hbm2java
 */
public class Karyawan  implements java.io.Serializable {


     private String idKaryawan;
     private String namaDepan;
     private String namaBelakang;
     private int gaji;

    public Karyawan() {
    }

    public Karyawan(String idKaryawan, String namaDepan, String namaBelakang, int gaji) {
       this.idKaryawan = idKaryawan;
       this.namaDepan = namaDepan;
       this.namaBelakang = namaBelakang;
       this.gaji = gaji;
    }
   
    public String getIdKaryawan() {
        return this.idKaryawan;
    }
    
    public void setIdKaryawan(String idKaryawan) {
        this.idKaryawan = idKaryawan;
    }
    public String getNamaDepan() {
        return this.namaDepan;
    }
    
    public void setNamaDepan(String namaDepan) {
        this.namaDepan = namaDepan;
    }
    public String getNamaBelakang() {
        return this.namaBelakang;
    }
    
    public void setNamaBelakang(String namaBelakang) {
        this.namaBelakang = namaBelakang;
    }
    public int getGaji() {
        return this.gaji;
    }
    
    public void setGaji(int gaji) {
        this.gaji = gaji;
    }
}


